openapi: 3.0.3
info:
  title: Stock and Order API
  description: API for confirming stock and placing orders
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /confirm-stock:
    post:
      summary: Confirm stock availability
      operationId: confirmStock
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmStockDto'
      responses:
        '200':
          description: Stock confirmation message published successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublishMessageResponse'
        '400':
          description: Invalid request body
        '500':
          description: Internal server error

  /place-order:
    post:
      summary: Place an order
      operationId: placeOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlaceOrderDto'
      responses:
        '200':
          description: Order message published successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublishMessageResponse'
        '400':
          description: Invalid request body
        '500':
          description: Internal server error

components:
  schemas:
    ConfirmStockDto:
      type: object
      properties:
        productId:
          type: string
          description: ID of the product to confirm stock
        quantity:
          type: integer
          description: Quantity to confirm
      required:
        - productId
        - quantity
      example:
        productId: "12345"
        quantity: 100

    PlaceOrderDto:
      type: object
      properties:
        orderId:
          type: string
          description: ID of the order to be placed
        productId:
          type: string
          description: ID of the product in the order
        quantity:
          type: integer
          description: Quantity of the product in the order
      required:
        - orderId
        - productId
        - quantity
      example:
        orderId: "54321"
        productId: "12345"
        quantity: 50

    PublishMessageResponse:
      type: object
      properties:
        messageKey:
          type: string
          description: Key of the published message
        messageId:
          type: string
          description: ID of the published message
      example:
        messageKey: "confirm-stock-12345"
        messageId: "message-67890"
